language: node_js
node_js:
- '11'
addons:
  sonarcloud:
    organization: soprasteria
cache:
  directories:
  - "$HOME/.sonar/cache"
  - node_modules
install:
- npm install
script:
- npm test
- node index.js --help
